[build]
  base    = ""
  publish = "build"
  command = "curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh && deno run --unstable --import-map=import_map.json -A ./scripts/build.ts"
